project:
  type: website
  output-dir: docs

website:
  title: "Ming Jun's Portfolio"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: project.qmd
      - text: "Data Visualization"
        href: data.qmd
      - text: "Reflection"
        href: reflection.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "GitHub"
        href: https://github.com/SMingJun-source
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/mingjun1998/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



